name: 'Execução Manual - Testes API'

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalando Yarn
        run:  npm i -g yarn

      - name: Instalando dependências
        run:  yarn install
        
      - name: Instalando dependências
        run:  yarn add --dev jest supertest


      - name: Executando testes de API
        run: yarn test

      - name: Upload do relatório de testes
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: ./test-report
